# Geographic adjacency between territories (undirected). Keys must match sheet names exactly.
ADJ = {
"Dallas Ft Worth": ["Killeen, TX","Houston","San Antonio","OKC/Arkansas","Tulsa, OK","N Louisiana","New Mexico"],
"Killeen, TX": ["Dallas Ft Worth","San Antonio","Houston"],
"San Antonio": ["Killeen, TX","Houston","Dallas Ft Worth"],
"Houston": ["Killeen, TX","San Antonio","Dallas Ft Worth","N Louisiana","New Orleans"],
"New Orleans": ["Houston","N Louisiana","Alabama","Memphis, TN"],
"N Louisiana": ["Dallas Ft Worth","Houston","New Orleans","OKC/Arkansas","Memphis, TN"],
"OKC/Arkansas": ["Tulsa, OK","Dallas Ft Worth","Kansas/NE/IA","N Louisiana","Memphis, TN","St Louis","New Mexico"],
"Tulsa, OK": ["OKC/Arkansas","Dallas Ft Worth","Kansas/NE/IA","St Louis"],
"Kansas/NE/IA": ["OKC/Arkansas","Tulsa, OK","St Louis","Minnesota/North Dakota","Chicago","Wisconsin","Denver Direct","Denver Distributor"],
"St Louis": ["OKC/Arkansas","Tulsa, OK","Kansas/NE/IA","Chicago","Indiana","Memphis, TN"],

"Chicago": ["Wisconsin","Indiana","Michigan","St Louis","Kansas/NE/IA"],
"Wisconsin": ["Chicago","Minnesota/North Dakota","Michigan","Kansas/NE/IA"],
"Minnesota/North Dakota": ["Wisconsin","Kansas/NE/IA"],
"Michigan": ["Chicago","Wisconsin","Indiana","Cleveland","Columbus"],
"Indiana": ["Chicago","Michigan","Columbus","Dayton/Cincinnati","St Louis","Cleveland"],
"Columbus": ["Indiana","Michigan","Cleveland","Dayton/Cincinnati","Pittsburgh","Western MD"],
"Cleveland": ["Columbus","Michigan","Indiana","Pittsburgh","Western NY"],
"Dayton/Cincinnati": ["Columbus","Indiana","Nashville, TN","East TN","Western MD","Pittsburgh"],

"Pittsburgh": ["Cleveland","Columbus","Western NY","Central PA","Western MD","Dayton/Cincinnati"],
"Central PA": ["Pittsburgh","Eastern PA","Western NY","Hudson River Valley","Western MD","Philadelphia & Southern NJ"],
"Eastern PA": ["Central PA","Philadelphia & Southern NJ","Northern NJ","Hudson River Valley"],
"Philadelphia & Southern NJ": ["Eastern PA","Central PA","Northern NJ","Delaware","Western MD"],
"Delaware": ["Philadelphia & Southern NJ","Western MD","Northern NJ"],
"Western MD": ["Pittsburgh","Central PA","Philadelphia & Southern NJ","Delaware","Columbus","Dayton/Cincinnati","Raleigh/Durham"],
"Northern NJ": ["Eastern PA","Philadelphia & Southern NJ","NYC","Hudson River Valley","Delaware"],
"NYC": ["Northern NJ","Long Island","Hudson River Valley"],
"Long Island": ["NYC","New England"],
"Hudson River Valley": ["NYC","Northern NJ","Capital Territory","Central PA","Eastern PA","Western NY"],
"Capital Territory": ["Hudson River Valley","New England","Western NY"],
"Western NY": ["Capital Territory","Hudson River Valley","Central PA","Pittsburgh","Cleveland"],
"New England": ["Long Island","Capital Territory","Hudson River Valley"],

"Nashville, TN": ["East TN","Memphis, TN","Alabama","Dayton/Cincinnati","Atlanta North"],
"East TN": ["Nashville, TN","Atlanta North","Charlotte, NC","Raleigh/Durham","Dayton/Cincinnati","Augusta, GA"],
"Memphis, TN": ["Nashville, TN","Alabama","N Louisiana","OKC/Arkansas","St Louis","New Orleans"],
"Alabama": ["Nashville, TN","Memphis, TN","New Orleans","Atlanta North","Atlanta South","FL Panhandle","Augusta, GA"],
"FL Panhandle": ["Alabama","Jacksonville","Tampa North","Atlanta South"],
"Jacksonville": ["FL Panhandle","Orlando North","Atlanta South","Augusta, GA","Charleston, SC"],
"Orlando North": ["Jacksonville","Orlando South","Tampa North","Tampa South"],
"Orlando South": ["Orlando North","Tampa South","West Palm","Tampa North"],
"Tampa North": ["Tampa South","Orlando North","FL Panhandle","Orlando South"],
"Tampa South": ["Tampa North","Orlando South","Orlando North","West Palm"],
"West Palm": ["Orlando South","Tampa South"],
"Atlanta North": ["Atlanta South","Augusta, GA","East TN","Nashville, TN","Alabama","Charlotte, NC"],
"Atlanta South": ["Atlanta North","Augusta, GA","Alabama","FL Panhandle","Jacksonville"],
"Augusta, GA": ["Atlanta North","Atlanta South","Charleston, SC","Charlotte, NC","Jacksonville","East TN"],
"Charleston, SC": ["Augusta, GA","Charlotte, NC","Raleigh/Durham","Jacksonville"],
"Charlotte, NC": ["Charleston, SC","Augusta, GA","Atlanta North","East TN","Raleigh/Durham"],
"Raleigh/Durham": ["Charlotte, NC","Charleston, SC","East TN","Western MD"],

"Bay Area": ["Sacramento","Fresno","Reno","North LA","Hawaii"],
"Sacramento": ["Bay Area","Fresno","Reno","Oregon"],
"Fresno": ["Bay Area","Sacramento","North LA","Las Vegas","Reno"],
"Reno": ["Sacramento","Bay Area","Fresno","Oregon","Idaho","Las Vegas","Utah"],
"North LA": ["Fresno","Los Angeles","Inland Empire","Bay Area"],
"Los Angeles": ["North LA","Orange County","Inland Empire","Hawaii"],
"Orange County": ["Los Angeles","Inland Empire","San Diego"],
"Inland Empire": ["Los Angeles","Orange County","San Diego","North LA","Las Vegas","Arizona","Fresno"],
"San Diego": ["Orange County","Inland Empire","Arizona"],
"Hawaii": ["Bay Area","Los Angeles"],
"Las Vegas": ["Inland Empire","Arizona","Utah","Reno","Fresno"],
"Arizona": ["Las Vegas","San Diego","Inland Empire","Utah","New Mexico"],
"Utah": ["Las Vegas","Arizona","Idaho","Reno","Denver Direct","Denver Distributor","New Mexico"],
"Idaho": ["Utah","Reno","Oregon","Washington","Denver Direct","Denver Distributor"],
"Oregon": ["Washington","Idaho","Reno","Sacramento"],
"Washington": ["Oregon","Idaho"],
"New Mexico": ["Arizona","Utah","Denver Direct","Denver Distributor","Dallas Ft Worth","OKC/Arkansas"],
"Denver Direct": ["Denver Distributor","Utah","New Mexico","Kansas/NE/IA","Idaho"],
"Denver Distributor": ["Denver Direct","Utah","New Mexico","Kansas/NE/IA","Idaho"],
}
def symmetrize():
    for k,v in list(ADJ.items()):
        for n in v:
            ADJ.setdefault(n,[])
            if k not in ADJ[n]: ADJ[n].append(k)
symmetrize()
